### ISSUE TITLE
[windows] Cannot extract publisher name from code signing certificate. As workaround, set win.publisherName.

### ISSUE THREAD

**Issue by lordgreg** [apache/cordova-electron#209]
# Bug Report

### What is expected to happen?
Get a signed version of appx or msi file.

### What does actually happen?
Exception is being thrown:
```
  • cannot decode PKCS 12 data using Go pure implementation, openssl will be used  error=pkcs12: unknown digest algorithm: 2.16.840.1.101.3.4.2.1
  ⨯ no certificates with ExtKeyUsageCodeSigning  
Cannot extract publisher name from code signing certificate. As workaround, set win.publisherName. Error: Error: C:\Users\ci-windows\Downloads\demos\ionic-v5\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (C:\Users\ci-windows\Downloads\demos\ionic-v5\node_modules\builder-util\src\util.ts:249:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

## Information

build.json:
```
{
  "electron": {
      "windows": {
          "package": [ "appx" ],
          "signing": {
            "release": {
              "certificateFile": "my-certificate.pfx"
            }
          }
      }
  }
}
```

pasword for cert is stored in `$env:CSC_KEY_PASSWORD`.

### Additional information here:
* You can build unsigned app without any problems
* Adding PFX certificate leads to the exception being thrown
* Adding win.publisherName doesn't do anything
* Removing the build.json completely and using only package.json works but builds only NSIS even if adding information to build.json or package.json.

### Command or Code

1. `npx cordova platform add electron@3.0.0`
2. `npx cordova build electron --release`
3. See exception above.

### Environment, Platform, Device

Windows 10 64-bit, intel-based cpu.

### Version information

Output from package.json:
```
    "cordova": "10.0.0",
    "cordova-android": "^9.0.0",
    "cordova-electron": "^3.0.0",
    "cordova-ios": "^6.1.0",
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
This issue seems to be related to this: https://github.com/electron-userland/electron-builder/issues/3467#issuecomment-580164063

When you are setting the `publisherName`, are you using the exact same value defined in the signing cert as the common name?

**Comment by erisu** [comment]
Also, when setting the `publisherName`, in a Cordova project, it should be set like this. The `win.publisherName` is in reference to the `electron-builder` scope...

```
{
  "electron": {
    "windows": {
      "publisherName": "ADD publisherName HERE",
      "package": [ "appx" ],
      "signing": {
        "release": {
          "certificateFile": "my-certificate.pfx"
        }
      }
    }
  }
}
```

You can confirm that it is being set when you view the file `platforms/electron/build/builder-effective-config.yaml` which the builder uses.

**Comment by lordgreg** [comment]
Hi @erisu and thank ouy for your feedback. I've found a bug.

When building/specifying the target "appx", the publisherName is written in `builder-effective-config.yaml` under `win`. However, reading electron-builder (https://www.electron.build/configuration/appx)[docs several time], `appx` should have its own configuration written in `builder-effective-config.yaml`. That is why the appx cannot be signed as such and throws an exception.

Wrong:
```
directories:
  output: XXX\ionic-v5\platforms\electron\build
  buildResources: XXX\ionic-v5\platforms\electron\build-res
  app: XXX\ionic-v5\platforms\electron\www
win:
  target:
    - target: appx
      arch:
        - x64
  icon: installer.png
publisherName: INFO_FROM_CERT
appId: snoot.boop
productName: boop a snoot
electronVersion: 14.0.0
electronDownload:
  version: 14.0.0
files: []
```

Correct:
```
directories:
  output: XXX\ionic-v5\platforms\electron\build
  buildResources: XXX\ionic-v5\platforms\electron\build-res
  app: XXX\ionic-v5\platforms\electron\www
appx:
  publisher: SUBJECT_FROM_CERT
win:
  target:
    - target: appx
      arch:
        - x64
  icon: installer.png
appId: snoot.boop
productName: boop a snoot
electronVersion: 14.0.0
electronDownload:
  version: 14.0.0
files: []
```

### Current workaround:
1. create build.json without any other addition except target:
```
{
  "electron": {
    "windows": {
      "package": [
        "appx"
      ]
    }
  }
}
```
2. update package.json and add this content to it:
```
  "build": {
    "appx": {
      "publisher": SUBJECT_FROM_CERTIFICATE (ex: CN=aaa,E=foo@bar,O=aaa...)
    }
  }
```
3. run cordova electorn build: `npx cordova build electron --release`
4. Then use windows SignTool to sign:
```
SignTool sign /tr http://timestamp.digicert.com /fd SHA256 /a /f CERTIFICATE.pfx /p PASSWORD "platforms\electron\build\*.appx"
```
5. Success.

**Comment by erisu** [comment]
Per electron-builder docs the location of publisherName is correct.

> publisherName String | Array<String> - The publisher name, exactly as in your code signed certificate. Several names can be provided. Defaults to common name from your code signing certificate.

https://www.electron.build/configuration/win

And is something used for all Windows target builds, but the option your talking about completely different.

> publisher String - The Windows Store publisher. Not used if AppX is build for testing. See AppX Package Code Signing below.

https://www.electron.build/configuration/appx

Now that I know what your looking for, this might work for you as well:

```json
{
  "electron": {
    "windows": {
      "package": [ { 
          "appx": {
            "publisher": "add here publisher data"
          }
        } ],
      "signing": {
        "release": {
          "certificateFile": "my-certificate.pfx"
        }
      }
    }
  }
}
```
But seems you have a working solution anyways. But if you can confirm the above that will help out.

**Comment by lordgreg** [comment]
Hi And thank you for your feedback. I've tested the json you provided:
```
{
  "electron": {
    "windows": {
      "publisherName": "INFO_FROM_CERTIFICATE",
      "package": [
        { 
          "appx": {
            "publisher": "INFO_FROM_CERTIFICATE"
          }
        } 
      ],
      "signing": {
        "release": {
          "certificateFile": "my-cert.pfx"
        }
      }
    }
  }
}
```

As you see, I've also added publisherName, since, the build job complained again:
```
  • electron-builder  version=22.11.7 os=10.0.19043
  • writing effective config  file=platforms\electron\build\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=14.0.0 appOutDir=platforms\electron\build\win-unpacked
  • signing         file=platforms\electron\build\win-unpacked\some name.exe certificateFile=mway-internal-original.pfx
  • building        target=AppX arch=x64 file=platforms\electron\build\some name 0.0.1.appx
  • cannot decode PKCS 12 data using Go pure implementation, openssl will be used  error=pkcs12: unknown digest algorithm: 2.16.840.1.101.3.4.2.1
  ⨯ no certificates with ExtKeyUsageCodeSigning  
Cannot extract publisher name from code signing certificate. As workaround, set win.publisherName.
```
That being said, adding publisherName, even with written data in effective-config.yaml, still yields the same exception.

**Comment by erisu** [comment]
It is a bit confusing why it is failing. It feels like a bug in the `electron-builder` tool...

Here is my example test run locally:

**build.json**

```json
{
  "electron": {
    "windows": {
      "publisherName": "TEST",
      "package": [
        {
          "appx": {
            "publisher": "TEST"
          }
        }
      ]
    }
  }
}
```

For my test, I am exclusing the signing information because I dont have a pfx. I am just confirming the `builder-effective-config.yaml` is correct.

When running, with the above settings, `electron-builder` creates this yaml file.

```yaml
directories:
  output: C:\Users\cordova\cordovaTest\platforms\electron\build
  buildResources: C:\Users\cordova\cordovaTest\platforms\electron\build-res
  app: C:\Users\cordova\cordovaTest\platforms\electron\www
appId: io.cordova.hellocordova
productName: HelloCordova
electronVersion: 14.0.0
electronDownload:
  version: 14.0.0
win:
  target:
    - target: appx
      arch:
        - x64
  icon: installer.png
  publisherName: TEST
appx:
  publisher: TEST
files: []
```

As seen above, it has the `publisher` option under `appx` and the `publisherName` under `win`, which is all expected.

Now why does it not work but works if the publisher info is defined in the `package.json` is the question.
